import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { data } from '@/data'
const inter = Inter({ subsets: ['latin'] })
import React, { useState } from 'react'

export default function Home() {
  const [name, setName] = useState('')
  const [user, setUser] = useState(data)
  const [loading, setLoading] = useState(false)

  const handleSubmit = () => {
    setTimeout(() => {
      if (!name) {
        return
      }
      const newUser = { id: new Date().getTime().toString(), name }
      setUser([...user, newUser])
      setName('')
      setLoading(false)
    }, 1000)
  }



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='my-4 shadow-lg p-3 mb-5 bg-body container text-center' style={ { maxWidth: '500px' } }>
        <h2 className='font-monospace'>Add User</h2>
        <input className='form-input my-4' id='name' type="text" value={ name } onChange={ (e) => setName(e.target.value) } />
        <br />
        {/* { loading ?
          <button class="btn btn-warning" type="button" disabled>
            <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
            Loading...
          </button>
          : */}
        <button className='btn btn-warning' type="button" onClick={ () => { (handleSubmit(), setLoading(true)) } }>Add Name</button>
        {/* } */ }
      </main>
      <section className='text-center mt-4 my-3'>
        { loading ?


          <div className="spinner-border" style={ { width: '10rem', height: '10rem' } } role="status">
            <span className="visually-hidden">Loading...</span>
          </div>
          :
          <>
            <h3 className='mb-4'>Users</h3>
            { user.map((item, index) => {
              return (
                <>
                  <div key={ item.id } className='d-flex justify-content-evenly my-4 font-monospace'>
                    <span className='mx-4'>{ index + 1 }</span>
                    <span>{ item.name }</span>
                    <button className='btn btn-danger mx-4' type="button" onClick={ () =>

                      setUser(user.filter((user) => user.id !== item.id))

                    }>Delete</button>
                  </div>
                </>
              )
            }) }
          </>
        }

      </section>
    </>
  )
}
